Garbage Collection in del function, Updated union of lists function
eclipse/agileuml pull request #3
Opened 2022-05-19 13:08 UTC by vijay-jaisankar

In this PR, the following changes have been implemented:

- Updated the `unionSequence` function in `ocl.py`
- Added an explicit call to the garbage collection module in the `free` function of `oclfile.py`; this should make things a little more efficient.

2025-01-09 11:32 UTC, Zishan-Rahman requested changes
@vijay-jaisankar (sorry for the ping) The garbage collection code is perfectly fine to merge. However, the unionSequence function is _meant_ to contain duplicates. [This mirrors how the union function in Acceleo's implementation of OCL, according to the UML standard, behaves with Sequences.](https://wiki.eclipse.org/Acceleo/OCL_Operations_Reference#union_.28_seq_:_Sequence.28T.29_.29_:_Sequence.28T.29) For example, `Sequence{'bbb', 'b'}->union({'b', 'bb'})` should evaluate to `Sequence{'bbb', 'b', 'b', 'bb'}`. If you still want this merged, please can you undo the unionSequence modification and push your changes here so that @kevinlano can merge them (I'm one of his PhD students)?

2025-01-12 10:25 UTC, kevinlano approved these changes
Change to oclfile.py is approved, but not to ocl.py

2025-01-12 10:26 UTC, merged

2025-01-12 10:30 UTC, vijay-jaisankar commented
Hello, thanks for the information about the implementation of the OCL. Sure, I can make another commit to this PR if you'd like reverting the change to the mentioned file.

2025-01-12 10:35 UTC, Zishan-Rahman commented
> Hello, thanks for the information about the implementation of the OCL. Sure, I can make another commit to this PR if you'd like, reverting the change to the mentioned file.

@vijay-jaisankar Looks like @kevinlano has already merged this PR just now, so feel free to create another PR reversing the ocl.py union changes.

2025-02-15 19:22 UTC, vijay-jaisankar commented
Hello, this change has been implemented in #19 , please have a look. Sorry for the delay, was off Github for a while.

> > Hello, thanks for the information about the implementation of the OCL. Sure, I can make another commit to this PR if you'd like, reverting the change to the mentioned file.
> 
> @vijay-jaisankar Looks like @kevinlano has already merged this PR just now, so feel free to create another PR reverting the ocl.py union changes.